#   _____
#  |  __ \
#  | |__) | __ _____  ___   _
#  |  ___/ '__/ _ \ \/ / | | |
#  | |   | | | (_) >  <| |_| |
#  |_|   |_|  \___/_/\_\\__, |
#                        __/ |
#                       |___/

# Dies ist die zentrale Konfigurationsdatei des Proxy-Plugins made by Merry & Tobi.
# Fehler sind unter der URL http://gitlab.syplex.eu:8080/Merry/Proxy/issues als Issue zu melden.

# Placeholder müssen in den entsprechenden Konfigurationen verwendet werden, sofern dies durch die Standardkonfigurationsdatei vorgegeben ist!
# Diese Konfigurationsdatei verwendet legacy Farbcodes zur Darstellung von Farben. Bei Bedarf ist eine Implementierung der Farbcodes von
# der Adventure API (https://docs.advntr.dev/) möglich. Hierfür bitte ebenfalls ein neues Issue erstellen.

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR DIE VERBINDUNG ZUR DATENBANK WICHTIG IST
#

# Der Hostname, unter dem die Datenbank erreichbar ist. Kann sowohl eine IP-Adresse, als auch eine Domain sein.
db-host: "127.0.0.1"

# Der Port, auf den die Datenbank hört
db-port: "3306"

# Der Name der Datenbank, auf die zugegriffen werden soll
db-database: "proxy"

# Der Benutzername des Kontos, welche für den Datenbankzugriff verwendet wird. "root" wird aus Gründen der Sicherheit nicht empfohlen.
db-username: "root"

# Das Passwort des Benutzerkontos. Falls nicht gesetzt, bitte die Konfiguration hier leer stehen lassen.
db-password: ""

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR MINECRAFT RELEVANT IST
#

# Nachricht, welche gesendet wird, wenn die Syntax eines Befehls nicht korrekt genutzt wurde.
# Placeholder:
#   - %command% - Die korrekte Syntax, die zu nutzen ist
invalid-usage: "&cBitte benutze &6/%command%&c!"

# Nachricht, welche gesendet wird, wenn der Spieler, der den Befehl nutzt, dazu keine Rechte hat.
no-permission: "&cDazu hast du keine Rechte!"

# Nachricht, welche gesendet wird, wenn der Befehl nicht durch einen Spieler benutzt wurde.
no-player: "&cDazu musst du ein Spieler sein!"

# Nachricht, welche gesendet wird, wenn ein abgefragter Spieler nicht auf dem Server online ist.
not-online: "&cDieser Spieler ist nicht online!"

# Nachricht, welche gesendet wird, wenn ein Spieler den Ping Befehl nutzt.
# Placeholder:
#   - %ping% - Der Ping des Spielers
ping: "&7Dein Ping beträgt &6%ping%ms"

# Erster Teil der Nachricht, welche gesendet wird, wenn ein Spieler den YouTube Befehl nutzt. Dieser Teil ist nicht anklickbar.
youtube-non-clickable: "&7Unsere Anforderungen an YouTuber findet du"

# Zweiter Teil der Nachricht, welche gesendet wird, wenn ein Spieler den YouTube Befehl nutzt. Dieser Teil ist anklickbar.
youtube-clickable: "&a [Hier]"

# URL, auf die der Spieler weitergeleitet werden soll, wenn auf den klickbaren Teil der YouTube Befehlsnachricht geklickt wurde
youtube-requirements-url: "https://syplex.eu/forum"

# Nachricht, welche dem Spieler auf dem Screen angezeigt wird, wenn er vom Server gekickt wurde.
got-kicked: "&cDu wurdest gekickt!"




