#   _____
#  |  __ \
#  | |__) | __ _____  ___   _
#  |  ___/ '__/ _ \ \/ / | | |
#  | |   | | | (_) >  <| |_| |
#  |_|   |_|  \___/_/\_\\__, |
#                        __/ |
#                       |___/

messages:
  invalid-usage: "<red>Bitte benutze <gold>%command%"
  no-permission: "<red>Dazu hast du keine Rechte!"
  no-player: "<red>Dazu musst du ein Spieler sein!"
  ping: "<grey>Dein Ping beträgt <gold>%ping%ms"
  youtube: "<grey>Unsere Anforderungen an YouTuber findet du"
  youtube-clickable: "<green> [Hier]"
urls:
  youtube: "https://syplex.eu/forum"


