#   _____
#  |  __ \
#  | |__) | __ _____  ___   _
#  |  ___/ '__/ _ \ \/ / | | |
#  | |   | | | (_) >  <| |_| |
#  |_|   |_|  \___/_/\_\\__, |
#                        __/ |
#                       |___/

# Dies ist die zentrale Konfigurationsdatei des Proxy-Plugins made by Merry & Tobi.
# Fehler sind unter der URL http://gitlab.syplex.eu:8080/Merry/Proxy/issues als Issue zu melden.

# Placeholder müssen in den entsprechenden Konfigurationen verwendet werden, sofern dies durch die Standardkonfigurationsdatei vorgegeben ist!
# Diese Konfigurationsdatei verwendet legacy Farbcodes zur Darstellung von Farben. Bei Bedarf ist eine Implementierung der Farbcodes von
# der Adventure API (https://docs.advntr.dev/) möglich. Hierfür bitte ebenfalls ein neues Issue erstellen.

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR DIE VERBINDUNG ZUR DATENBANK WICHTIG IST!
#
# Hinweis: Die hier gesetzten Standardwerte werden ebenfalls verwendet, wenn die Konfiguration nicht geladen werden konnte.
#

# Der Hostname, unter dem die Datenbank erreichbar ist. Kann sowohl eine IP-Adresse, als auch eine Domain sein.
db-host: "dev.syplex.eu"

# Der Port, auf den die Datenbank hört
db-port: "3306"

# Der Name der Datenbank, auf die zugegriffen werden soll
db-database: "devtest"

# Der Benutzername des Kontos, welche für den Datenbankzugriff verwendet wird. "root" wird aus Gründen der Sicherheit nicht empfohlen.
db-username: "merry"

# Das Passwort des Benutzerkontos. Falls nicht gesetzt, bitte die Konfiguration hier leer stehen lassen.
db-password: "JDqoxWvdjwSj8RBaiE855wQ9LJ6y3m4tARN4r3QVQwVVEtD2"

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR MINECRAFT RELEVANT IST!
#

# Nachricht, welche gesendet wird, wenn die Syntax eines Befehls nicht korrekt genutzt wurde.
# Placeholder:
#   - %command% - Die korrekte Syntax, die zu nutzen ist
invalid-usage: "&cBitte benutze &6/%command%&c!"

# Nachricht, welche gesendet wird, wenn der Spieler, der den Befehl nutzt, dazu keine Rechte hat.
no-permission: "&cDazu hast du keine Rechte!"

# Nachricht, welche gesendet wird, wenn der Befehl nicht durch einen Spieler benutzt wurde.
no-player: "&cDazu musst du ein Spieler sein!"

# Nachricht, welche gesendet wird, wenn ein abgefragter Spieler nicht gefunden wird
player-not-existent: "&cDieser Spieler ist nicht bei uns registriert!"

# Nachricht, welche gesendet wird, wenn ein abgefragter Spieler nicht auf dem Server online ist.
not-online: "&cDieser Spieler ist nicht online!"

# Nachricht, welche gesendet wird, wenn ein Spieler den Ping Befehl nutzt.
# Placeholder:
#   - %ping% - Der Ping des Spielers
ping: "&7Dein Ping beträgt &6%ping%ms"

# Erster Teil der Nachricht, welche gesendet wird, wenn ein Spieler den YouTube Befehl nutzt. Dieser Teil ist nicht anklickbar.
youtube-non-clickable: "&7Unsere Anforderungen an YouTuber findet du"

# Zweiter Teil der Nachricht, welche gesendet wird, wenn ein Spieler den YouTube Befehl nutzt. Dieser Teil ist anklickbar.
youtube-clickable: "&a [Hier]"

# URL, auf die der Spieler weitergeleitet werden soll, wenn auf den klickbaren Teil der YouTube Befehlsnachricht geklickt wurde
youtube-requirements-url: "https://syplex.eu/forum"

# Nachricht, welche dem Spieler gesendet wird, wenn er einen Spieler erfolgreich vom Server gekickt hat.
kick: "&7Du hast den Spieler &6%player% &cvom Server gekickt."

# Nachricht, welche dem Spieler gesendet wird, wenn er einen Spieler erfolgreich vom Server gekickt und einen Grund angegeben hat.
# Placeholder:
#   - %player% - Der Name des gekickten Spielers
#   - %reason% - Der Grund, warum der Spieler gekickt wurde
kick-with-reason: "&7Du hast den Spieler &6%player% &7wegen &6%reason% &cvom Server gekickt."

# Nachricht, welche dem Spieler auf dem Screen angezeigt wird, wenn er vom Server gekickt wurde.
kick-disconnect: "&cDu wurdest gekickt!"

# Nachricht, welche dem Spieler gesendet wird, wenn die angegebene ID keine Zahl ist
id-format-error: "&cDie ID muss eine gültige Zahl sein!"

# Nachricht, welche dem Spieler auf dem Screen angezeigt wird, wenn er vom Server gebannt wurde.
ban-disconnect: "&cDu wurdest gebannt."

# Nachricht, die gesendet wird, wenn ein Spieler gebannt wurde
ban-banned: "&aDu hast &c%player% &agebannt."

# Nachricht, welche dem Spieler gesendet wird, falls der zu bannende Spieler bereits gebannt ist.
already-banned: "&cDieser Spieler ist bereits gebannt!"

# Nachricht, welche gesendet wird, wenn ein Spieler nicht gebannt ist.
not-banned: "&cDieser Spieler ist nicht gebannt!"

# Erste Zeile des Bann-Screens
# Placeholder:
#   - %duration% - Die Länge des Banns
ban-screen-line-1: "&cDu wurdest &4%duration% &cvon Syplex.eu gebannt."

# Zweite Zeile des Bann-Screens
# Placeholder:
#   - %reason% - Der Banngrund
#   - %uid% - Die eindeutige ID des Banns
ban-screen-line-2: "&cGrund&7: &3%reason% &8[&7%uid%&8]"

# Dritte Zeile des Bann-Screens
# Placeholder:
#   - %url% - Die URL zum Entbannungsantrag
ban-screen-line-3: "&aDu kannst unter &e%url% &aeinen Entbannungsantrag stellen."

# URL zum Entbannungsantrag
unban-url: "https://account.syplex.eu"

# Zusätzliche Zeile zwischen der zweiten und dritten im Bann-Screen, falls der Bann nicht permanent ist
ban-screen-time-left: "&cVerbleibende Zeit&7: %expires%"

# Nachricht, die gesendet ird, wenn die eingegebene numerische ID nicht gefunden wurde
# Placeholder:
#   - %id% - Die ID
#   - %reason% - Der Name des Banngrundes
#   - %duration% - Die Länge des Banns
ban-id-not-found: "&cBann &8» &7%id%: %reason% &8» &e%duration%"

# Nachricht, welche gesendet wird, wenn ein Spieler entbannt wurde.
player-unbanned: "&aDu hast den Spieler &6%player% &aentbannt."

# Nachricht, die gesendet ird, wenn die eingegebene numerische ID nicht gefunden wurde
# Placeholder:
#   - %id% - Die ID
#   - %reason% - Der Name des Mutegrunds
#   - %duration% - Die Länge des Mutes
mute-id-not-found: "&cMute &8» &7%id%: %reason% &8» &e%duration%"

# Nachricht, welche dem Spieler gesendet wird, falls der zu mutende Spieler bereits gemutet ist.
already-muted: "&cDieser Spieler ist bereits gemutet!"

# Nachricht, welche gesendet wird, wenn ein Spieler nicht gemutet ist.
not-muted: "&cDieser Spieler ist nicht gemutet!"

# Nachricht, die gesendet wird, wenn ein Spieler gemutet wurde
mute-muted: "&aDu hast &c%player% &agemutet."

# Nachricht, welche gesendet wird, wenn ein Spieler entmutet wurde.
player-unmuted: "&aDu hast den Spieler &6%player% &aentmutet."

# Nachricht, wenn eine Nachricht in den Teamchat gesendet wird
# Placeholder:
#   - %player% - Der Name des Spielers, der die Nachricht geschickt hat
#   - %message% - Die Nachricht
teamchat: "&7[&5Team&7] &3%player% &8» &7%message%"
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR BANNS RELEVANT IST!
#
# Die im Folgenden definierten Längen sind in Sekunden anzugeben. -1 wird als permanent interpretiert.
# Eine Webseite zum Umrechnen von Tagen in Sekunden ist unter der URL https://www.unitjuggler.com/time-umwandeln-von-day-nach-ms.html aufrufbar.
#

# Banngrund mit der ID #1
ban-reason-1: "Hacking"

# Banngrund mit der ID #2
ban-reason-2: "Teaming"

# Banngrund mit der ID #3
ban-reason-3: "Unerlaubter Name"

# Banngrund mit der ID #4
ban-reason-4: "Unerlaubter Skin"

# Banngrund mit der ID #5
ban-reason-5: "Rassismus"

# Banngrund mit der ID #6
ban-reason-6: "Provokation"

# Banngrund mit der ID #7
ban-reason-7: "Extreme Beleidigung"

# Banngrund mit der ID #8
ban-reason-8: "Werbung"

# Banngrund mit der ID #9
ban-reason-9: "Accountliste"

# Banngrund mit der ID #10
ban-reason-10: "Bannumgehung"

# Banngrund mit der ID #11
ban-reason-11: "Reportausnutzung"

# Banngrund mit der ID #12
ban-reason-12: "Bugusing"

# Banngrund mit der ID #13
ban-reason-13: "Drohung"

# Banngrund mit der ID #14
ban-reason-14: "Custom Grund-1, änderbar in der Config"

# Banngrund mit der ID #15
ban-reason-15: "Custom Grund-2, änderbar in der Config"

# Länge des Banns mit der ID #1 in Sekunden
ban-duration-1: -1

# Länge des Banns mit der ID #2 in Sekunden
ban-duration-2: 1209600000

# Länge des Banns mit der ID #3 in Sekunden
ban-duration-3: 60480000

# Länge des Banns mit der ID #4 in Sekunden
ban-duration-4: 60480000

# Länge des Banns mit der ID #5 in Sekunden
ban-duration-5: 18144000

# Länge des Banns mit der ID #6 in Sekunden
ban-duration-6: 25920000

# Länge des Banns mit der ID #7 in Sekunden
ban-duration-7: 60480000

# Länge des Banns mit der ID #8 in Sekunden
ban-duration-8: 60480000

# Länge des Banns mit der ID #9 in Sekunden
ban-duration-9: -1

# Länge des Banns mit der ID #10 in Sekunden
ban-duration-10: -1

# Länge des Banns mit der ID #11 in Sekunden
ban-duration-11: 60480000

# Länge des Banns mit der ID #12 in Sekunden
ban-duration-12: 25920000

# Länge des Banns mit der ID #13 in Sekunden
ban-duration-13: 25920000

# Länge des Banns mit der ID #14 in Sekunden
ban-duration-14: -1

# Länge des Banns mit der ID #15 in Sekunden
ban-duration-15: -1

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR MUTES RELEVANT IST!
#
# Die im Folgenden definierten Längen sind in Sekunden anzugeben. -1 wird als permanent interpretiert.
#

# Mutegrund mit der ID #1
mute-reason-1: "Beleidigung | Teammitglied"

# Mutegrund mit der ID #2
mute-reason-2: "Beleidigung | Spieler"

# Mutegrund mit der ID #3
mute-reason-3: "Beleidigung | Server"

# Mutegrund mit der ID #4
mute-reason-4: "Verhalten | Respektlos"

# Mutegrund mit der ID #6
mute-reason-5: "Verhalten | Asozial"

# Länge des Banns mit der ID #1 in Sekunden
mute-duration-1: 60480000

# Länge des Banns mit der ID #2 in Sekunden
mute-duration-2: 60480000

# Länge des Banns mit der ID #3 in Sekunden
mute-duration-3: 60480000

# Länge des Banns mit der ID #4 in Sekunden
mute-duration-4: 60480000

# Länge des Banns mit der ID #5 in Sekunden
mute-duration-5: 60480000

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------
# AB HIER BEGINNT DER TEIL, WELCHER FÜR REPORTS RELEVANT IST!
#

# Reportgrund mit der ID #1
report-reason-1: "Hacking"

# Reportgrund mit der ID #2
report-reason-2: "Beleidigung"

# Reportgrund mit der ID #3
report-reason-3: "Skin"

# Reportgrund mit der ID #4
report-reason-4: "Name"

# Reportgrund mit der ID #5
report-reason-5: "Trolling"

# Reportgrund mit der ID #6
report-reason-6: "Spam"

# Reportgrund mit der ID #7
report-reason-7: "Werbung"